<a href="https://colab.research.google.com/github/prips47/google_colabs_files/blob/master/variables_constant_placeholders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import tensorflow as tf

In [0]:
#Explain the concepts constants using tensorflow code
a=tf.constant(3)
b=tf.constant(5)
c=a+b

#till. now we have only created computational graph; not executed

#invoke session to execute the graph
with tf.Session() as sess:
  outp1=sess.run(c)
  print(outp1)
  
#another way to execute the graph
tf.InteractiveSession()
print(c.eval())

8
8


In [0]:
#Explain the concepts of variables in tensorflow code
a=tf.Variable(0,name='input')
b=tf.constant(1)
temp=tf.add(a,b)
updated_value=tf.assign(a,temp);

#initialising the variables
tg=tf.initialize_all_variables()
with tf.Session() as sess:
  sess.run(tg)
  print(sess.run(a))
#executing the computational graph
  for i in range(4):
    sess.run(updated_value)
    print(sess.run(a))

0
1
2
3
4


In [0]:
 #Explain placeholders in tensorflow
  #imput is 2d matrix
  x=tf.placeholder("float32",[None,3]) # none means can be any value. in 1d array 
  #it's no of elements and in 2d array it's no. of rows
  y=x**2 #Y=square(x)
  
  with tf.Session() as sess:
    result=sess.run(y,feed_dict={x:[[1,2,3],[4,5,6]] })
    print(result)
    
    
#input is 1d matrix 
  x1=tf.placeholder("float32",3) # none means can be any value. in 1d array 
  #it's no of elements and in 2d array it's no. of rows
  y1=x1**2 #Y=square(x)
  a=input()
  b=input()
  c=input()
  feed_dict={x1:[a,b,c]}
  with tf.Session() as sess:
   # for i in range(3):
      result=sess.run(y1,feed_dict)
      print(result)
    
    


[[ 1.  4.  9.]
 [16. 25. 36.]]
2 
3
4
[ 4.  9. 16.]
